### PR TITLE
Remove finalizer if RBAC not available

### LINKED ISSUE #4769: Legacy Finalizer Blocks Namespace Deletion After Operator Upgrade
### Component(s)

collector

## Description
When OpenTelemetry Operator <= v0.141.0 and Custom Resource(operand) installed, the opentelemetry collector controller adds the finalizer `opentelemetrycollector.opentelemetry.io/finalizer` to the Custom Resource. This finalizer is not necessary in case of RBAC is not available. This is fixed in #4574 . Yet previously added finalizer is not removed which leads to preventing the successful namespace deletion.

## Steps to Reproduce

1. Install OpenTelemetry Operator <= v0.141.0
2. Install OpenTelemetry Collector (Custom Resource) -> This will add finalizer to CR
3. Upgrade OpenTelemetry Operator >= v0.142.0 -> #4574 is included which will ignore addition of finalizer to CR if RBAC is not available
 
## Expected Result
Finalizer must be removed if RBAC is not available

## Actual Result
Finalizer still exists as it was created by OpenTelemetry Operator <= v0.141.0

### Kubernetes Version

1.27.0

### Operator version

v0.141.0

### Collector version

v0.141.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell

```

### Additional context

Related to #4367 

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by smanojj**
- Remove legacy finalizer added by OpenTelemetry Operator <= v0.141.0 from CR if RBAC if not available
- Fixes #4769

### CODE REVIEW

File: internal/controllers/opentelemetrycollector_controller.go [hunk 1]
```diff
@@ -246,25 +246,29 @@ func (r *OpenTelemetryCollectorReconciler) Reconcile(ctx context.Context, req ct
...
-	if deletionTimestamp := instance.GetDeletionTimestamp(); deletionTimestamp != nil {
+	// Remove finalizer if RBAC permission not available
+	deletionTimestamp := instance.GetDeletionTimestamp()
+	if deletionTimestamp != nil || params.Config.CreateRBACPermissions != rbac.Available {
 		if controllerutil.ContainsFinalizer(&instance, collectorFinalizer) {
 			// If the finalization logic fails, don't remove the finalizer so
 			// that we can retry during the next reconciliation.
-			if err = r.finalizeCollector(ctx, params); err != nil {
+			err = r.finalizeCollector(ctx, params)
+			if err != nil && deletionTimestamp != nil {
```
Comment (swiatekm) [inline internal/controllers/opentelemetrycollector_controller.go]: Why are we dropping this error if `deletionTimestamp == nil`? Logically, what you're doing here doesn't just come up during the operator upgrade, but also when the RBAC config is changed. Failing to finalize or remove the finalizer should be reported like a normal error.

Comment (smanojj) [reply internal/controllers/opentelemetrycollector_controller.go]: I thought of retaining the same behavior as before when `deletionTimestamp != nil`. i.e., to return the results only during deletion

Comment (smanojj) [reply internal/controllers/opentelemetrycollector_controller.go]: Done

**Review by frzifus — APPROVED** [review]
