### PR TITLE
Propagate global scrape protocols by allowing for global config setting

### LINKED ISSUE #3160: Global scrape protocols not propagated to target allocator generated scrape configs
### Component(s)

target allocator

## Description
Similar to https://github.com/open-telemetry/opentelemetry-operator/issues/3035. When specifying scrape protocols in the global prometheus config for a collector, those protocols are not propagated to the generated scrape configs.

## Steps to Reproduce
Use a prometheus config with scrape protocols globally defined:
```
prometheus:
    config:
      global:
        scrape_interval: 30s
        scrape_protocols: ['PrometheusProto','OpenMetricsText1.0.0','OpenMetricsText0.0.1','PrometheusText0.0.4']
    target_allocator:
      endpoint: [http://opentelemetry-k8s-agent-targetallocator:80](http://opentelemetry-k8s-agent-targetallocator/)
      interval: 30s
      collector_id: ${POD_NAME}
      http_sd_config:
        refresh_interval: 60s
```

## Expected Result
Generated scrape configs have the `PrometheusProto` protocol included:
```
    "scrape_protocols": [
      "PrometheusProto",
      "OpenMetricsText1.0.0",
      "OpenMetricsText0.0.1",
      "PrometheusText0.0.4"
    ],
```

## Actual Result
`PrometheusProto` is omitted:
```
    "scrape_protocols": [
      "OpenMetricsText1.0.0",
      "OpenMetricsText0.0.1",
      "PrometheusText0.0.4"
    ],
```

### Kubernetes Version

1.28.3

### Operator version

v0.103.0

### Collector version

v0.103.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jaronoff97**
**Description:** Adjusts the TA CRD to allow for setting the global config

**Link to tracking Issue(s):**

- Resolves #3160

**Testing:** unit and e2e

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by jaronoff97** [comment]
I confirmed that running this new operator version resulted in this response from the scrape_configs endpoint
```
{
  "otel-collector": {
    "enable_compression": true,
    "enable_http2": true,
    "follow_redirects": true,
    "honor_timestamps": true,
    "job_name": "otel-collector",
    "metrics_path": "/metrics",
    "scheme": "http",
    "scrape_interval": "10s",
    "scrape_protocols": [
      "PrometheusProto",
      "OpenMetricsText1.0.0",
      "OpenMetricsText0.0.1",
      "PrometheusText0.0.4"
    ],
    "scrape_timeout": "10s",
    "static_configs": [
      {
        "targets": [
          "0.0.0.0:8888"
        ]
      }
    ],
    "track_timestamps_staleness": false
  }
}
```

File: apis/v1alpha1/targetallocator_types.go [hunk 1]
```diff
@@ -73,6 +73,9 @@ type TargetAllocatorSpec struct {
 	// +optional
 	// +kubebuilder:default:=relabel-config
 	FilterStrategy v1beta1.TargetAllocatorFilterStrategy `json:"filterStrategy,omitempty"`
+	// GlobalConfig configures the global configuration for Prometheus
+	// For the exact format, see https://github.com/prometheus/prometheus/blob/main/config/config.go#L409-L448
```
Comment (swiatekm) [inline apis/v1alpha1/targetallocator_types.go:77]: I think we should link to the Prometheus documentation here, rather than the struct definition: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file

**Review by swiatekm — APPROVED** [review]
LGTM, one nitpick about the attribute docstring.

**Review by pavolloffay — APPROVED** [review]
