### PR TITLE
[target-allocator] Update scrape config upon discovery config apply

### LINKED ISSUE #1359: [target allocator] Data race when writing / reading `jobToScrapeConfig` in `Discoverer`
When running the target allocator in our test environment, it would often crash for us with the following output (truncated to most relevant part):

```
{"level":"info","ts":1672998710.9367316,"logger":"allocator","msg":"Successfully started a collector pod watcher","component":"opentelemetry-targetallocator"}
fatal error: concurrent map read and map write

goroutine 6072 [running]:
reflect.mapaccess_faststr(0x23078e8?, 0x7f8e9acbcf38?, {0xc17459e450?, 0x34fba60?})
	/usr/local/go/src/runtime/map.go:1343 +0x1e
reflect.Value.MapIndex({0x2966a20?, 0xc000c80fc0?, 0xc17aa5f4a0?}, {0x273e3c0, 0xc1fd84bc30, 0x98})
	/usr/local/go/src/reflect/value.go:1664 +0xc5
github.com/mitchellh/hashstructure.(*walker).visit(0xc190f7f790, {0x2966a20?, 0xc000c80fc0?, 0xc000291d60?}, 0x0)
	/go/pkg/mod/github.com/mitchellh/hashstructure@v1.1.0/hashstructure.go:225 +0x1685
github.com/mitchellh/hashstructure.Hash({0x2966a20?, 0xc000c80fc0}, 0x8?)
	/go/pkg/mod/github.com/mitchellh/hashstructure@v1.1.0/hashstructure.go:108 +0x213
github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator/server.(*Server).ScrapeConfigsHandler(0xc000165860, {0x34f3110, 0xc3e789e460}, 0xc1fd84b5d0?)
	/app/server/server.go:93 +0x5c
net/http.HandlerFunc.ServeHTTP(0x100?, {0x34f3110?, 0xc3e789e460?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator/server.(*Server).PrometheusMiddleware.func1({0x34f3110, 0xc3e789e460}, 0xc5d6c20c60?)
	/app/server/server.go:138 +0x13f
net/http.HandlerFunc.ServeHTTP(0xc190c4ba00?, {0x34f3110?, 0xc3e789e460?}, 0x800?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f43c0, {0x34f3110, 0xc3e789e460}, 0xc190c4b900)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc5d6c20ae0?}, {0x34f3110, 0xc3e789e460}, 0xc190c4b900)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0a4573360, {0x34f46c0, 0xc0004a4180})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

After taking a look, it seems to me there's concurrent writing in `Discoverer`s `ApplyConfig` to the `jobToScrapeConfig` map and reading of this map via `GetScrapeConfigs()` in the scrape config handler during the hashing of the config. 

I'd suggest to protect the map with a mutex / return only a copy of the map for reading.

Somewhat related to similar issue in https://github.com/open-telemetry/opentelemetry-operator/pull/1040

### PR DESCRIPTION
**Pull request by matej-g**
Fixes #1359.

This is a proposed alternative to solve the data race issue in scrape config handler and at the same time now blowing up the memory on a repeated handler call.

The stored scrape config response gets updated only upon relevant changes in the `Discoverer`. When a change is detected, it calls a method to update the stored scrape config in the HTTP server response. All responses to scrape config handler are then served from this stored JSON response (or alternatively an error is returned if the latest config update failed). We also keep the hash of config within the discoverer, to prevent sending unnecessarily scrape configs over channel if no update has been detected.

Benchmarks from my machine:
```
goos: darwin
goarch: arm64
pkg: github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator/server
                                    │     old.txt     │            new_sync.txt             │
                                    │     sec/op      │    sec/op     vs base               │
ScrapeConfigsHandler/0_targets-10        1.929µ ± ∞ ¹   1.880µ ± ∞ ¹   -2.54% (p=0.032 n=5)
ScrapeConfigsHandler/5_targets-10      240.840µ ± ∞ ¹   2.107µ ± ∞ ¹  -99.13% (p=0.008 n=5)
ScrapeConfigsHandler/10_targets-10     452.602µ ± ∞ ¹   2.543µ ± ∞ ¹  -99.44% (p=0.008 n=5)
ScrapeConfigsHandler/50_targets-10    2246.603µ ± ∞ ¹   3.737µ ± ∞ ¹  -99.83% (p=0.008 n=5)
ScrapeConfigsHandler/100_targets-10   4672.521µ ± ∞ ¹   6.042µ ± ∞ ¹  -99.87% (p=0.008 n=5)
ScrapeConfigsHandler/500_targets-10   23730.46µ ± ∞ ¹   18.43µ ± ∞ ¹  -99.92% (p=0.008 n=5)
geomean                                  611.7µ         4.015µ        -99.34%
¹ need >= 6 samples for confidence interval at level 0.95

                                    │     old.txt     │             new_sync.txt             │
                                    │      B/op       │     B/op       vs base               │
ScrapeConfigsHandler/0_targets-10       6.376Ki ± ∞ ¹   6.423Ki ± ∞ ¹   +0.74% (p=0.008 n=5)
ScrapeConfigsHandler/5_targets-10     206.839Ki ± ∞ ¹   8.110Ki ± ∞ ¹  -96.08% (p=0.008 n=5)
ScrapeConfigsHandler/10_targets-10     311.29Ki ± ∞ ¹   10.36Ki ± ∞ ¹  -96.67% (p=0.008 n=5)
ScrapeConfigsHandler/50_targets-10    1651.12Ki ± ∞ ¹   24.36Ki ± ∞ ¹  -98.52% (p=0.008 n=5)
ScrapeConfigsHandler/100_targets-10   4117.17Ki ± ∞ ¹   46.37Ki ± ∞ ¹  -98.87% (p=0.008 n=5)
ScrapeConfigsHandler/500_targets-10   22878.4Ki ± ∞ ¹   182.4Ki ± ∞ ¹  -99.20% (p=0.008 n=5)
geomean                                 632.2Ki         21.93Ki        -96.53%
¹ need >= 6 samples for confidence interval at level 0.95

                                    │     old.txt     │            new_sync.txt            │
                                    │    allocs/op    │  allocs/op   vs base               │
ScrapeConfigsHandler/0_targets-10         24.00 ± ∞ ¹   23.00 ± ∞ ¹   -4.17% (p=0.008 n=5)
ScrapeConfigsHandler/5_targets-10       3396.00 ± ∞ ¹   23.00 ± ∞ ¹  -99.32% (p=0.008 n=5)
ScrapeConfigsHandler/10_targets-10      6702.00 ± ∞ ¹   23.00 ± ∞ ¹  -99.66% (p=0.008 n=5)
ScrapeConfigsHandler/50_targets-10     33144.00 ± ∞ ¹   23.00 ± ∞ ¹  -99.93% (p=0.008 n=5)
ScrapeConfigsHandler/100_targets-10    66208.00 ± ∞ ¹   23.00 ± ∞ ¹  -99.97% (p=0.008 n=5)
ScrapeConfigsHandler/500_targets-10   330516.00 ± ∞ ¹   23.00 ± ∞ ¹  -99.99% (p=0.008 n=5)
geomean                                  8.570k         23.00        -99.73%
¹ need >= 6 samples for confidence interval at level 0.95
```

### CODE REVIEW

File: cmd/otel-allocator/main.go [hunk 1]
```diff
@@ -209,6 +212,21 @@ func main() {
 			setupLog.Info("Closing watcher loop")
 			close(eventCloser)
 		})
+	runGroup.Add(
+		func() error {
+			for {
+				select {
+				case scrapeCfg := <-scrapeConfigChan:
+					srv.UpdateScrapeConfigResponse(scrapeCfg)
```
Comment (matej-g) [inline cmd/otel-allocator/main.go:220]: One thing I'm wondering is how to handle update failures such as unmarshalling. For now I tried to keep the behavior we have currently (return server error in the HTTP handler), but I wonder if we should not handle it here with `setupLog.Error` and keep returning last known good scrape configuration? Thoughts?

**Comment by matej-g** [comment]
I wonder now if there is actually need to do this over channel rather than doing this synchronously and just update the scrape config response directly from `Discoverer`

**Comment by jaronoff97** [comment]
yeah i'm not sure we need the channel here, you can do as we've done with [interfaces like the hook](https://github.com/open-telemetry/opentelemetry-operator/blob/main/cmd/otel-allocator/target/discovery.go#L45-L47) and just pass that around. Could you also add some tests for the UpdateScrapeConfigResponse? They'll probably look similar to the ones removed in the `TestScrapeConfigsHandler_Hashing`

**Comment by matej-g** [comment]
Yeah, I guess no reason to complicate it here, let me do that + add tests and come back with more commits

File: cmd/otel-allocator/main.go (hunk 1 above)
Comment (matej-g) [reply cmd/otel-allocator/main.go]: No longer an open question I guess

**Comment by matej-g** [comment]
I have updated the PR, the description and I'm undrafting this for reviews, thanks! cc @jaronoff97 @kristinapathak

File: cmd/otel-allocator/server/server.go [hunk 2]
```diff
@@ -93,38 +85,36 @@ func (s *Server) Shutdown(ctx context.Context) error {
...
+	}
+	s.scrapeConfigErr = nil
+	s.scrapeConfigResponse = jsonConfig
+}
+
+// ScrapeConfigsHandler returns the available scrape configuration discovered by the target allocator.
+func (s *Server) ScrapeConfigsHandler(c *gin.Context) {
+	response, err := s.scrapeConfigResponse, s.scrapeConfigErr
+	if err != nil {
+		s.errorHandler(c.Writer, s.scrapeConfigErr)
```
Comment (frzifus) [inline cmd/otel-allocator/server/server.go:112]: Can async reading `s.scrapeConfigErr` here and writing it in ` func UpdateScrapeConfigResponse` lead to some issues?

File: .chloggen/1413-cache-scrape-config-response.yaml [hunk 3]
```diff
@@ -0,0 +1,16 @@
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: enhancement
+
+# The name of the component, or a single word describing the area of concern, (e.g. operator, target allocator, github action)
+component: "target allocator"
+
+# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: "Save the scrape config response in the HTTP server upon relevant confif change, instead of building it on every handler call. At the same time, this avoids data race when accessing the scrape configs map."
```
Comment (frzifus) [inline .chloggen/1413-cache-scrape-config-response.yaml:8]:
```suggestion
note: "Save the scrape config response in the HTTP server upon relevant config change, instead of building it on every handler call. At the same time, this avoids data race when accessing the scrape configs map."
```

File: cmd/otel-allocator/server/server.go (hunk 2 above)
Comment (matej-g) [reply cmd/otel-allocator/server/server.go:112]: Good catch, I think actually I should put `err` here instead from `s.scrapeConfigErr`. That should ensure even if we change / remove the error cached on the HTTP server in the meantime, we won't put incorrect / nil error into the response.

File: cmd/otel-allocator/server/server.go [hunk 4]
```diff
@@ -48,26 +47,19 @@ type collectorJSON struct {
...
-	logger           logr.Logger
-	allocator        allocation.Allocator
-	discoveryManager DiscoveryManager
-	server           *http.Server
+	logger    logr.Logger
+	allocator allocation.Allocator
+	server    *http.Server
 
-	compareHash          uint64
 	scrapeConfigResponse []byte
```
Comment (jaronoff97) [inline cmd/otel-allocator/server/server.go:55]: I think we need a lock around the scrape config response to prevent concurrent access from the discovery manager?

File: cmd/otel-allocator/server/server.go [hunk 5]
```diff
@@ -93,38 +85,36 @@ func (s *Server) Shutdown(ctx context.Context) error {
...
-	configs := s.discoveryManager.GetScrapeConfigs()
-
-	hash, err := hashstructure.Hash(configs, nil)
+func (s *Server) UpdateScrapeConfigResponse(configs map[string]*promconfig.ScrapeConfig) {
+	var configBytes []byte
+	configBytes, err := yaml.Marshal(configs)
 	if err != nil {
-		s.logger.Error(err, "failed to hash the config")
-		s.errorHandler(c.Writer, err)
+		s.scrapeConfigErr = err
```
Comment (jaronoff97) [inline cmd/otel-allocator/server/server.go:95]: IMO we should return an error from here rather than store it, the discovery manager's method already has error handling baked in. This also means that if we see some type of bogus configuration here, we can bubble that up to the caller while still holding on to the last good configuration. In this case we'd want to store the hash only after a successful call to `UpdateScrapeConfigResponse`.

File: cmd/otel-allocator/target/discovery.go [hunk 6]
```diff
@@ -75,6 +79,17 @@ func (m *Discoverer) ApplyConfig(source allocatorWatcher.EventSource, cfg *confi
...
 	}
 
+	hash, err := hashstructure.Hash(m.jobToScrapeConfig, nil)
+	if err != nil {
+		return err
+	}
+	// If the hash has changed, updated stored hash and send the new config.
+	// Otherwise skip updating scrape configs.
+	if m.scrapeConfigsUpdater != nil && m.scrapeConfigsHash != hash {
+		m.scrapeConfigsHash = hash
```
Comment (jaronoff97) [inline cmd/otel-allocator/target/discovery.go:89]: as mentioned above, this should only come after our successful call to the `UpdateScrapeConfigResponse`

**Review by jaronoff97 — CHANGES_REQUESTED** [review]
Similar to @frzifus review, i had a few ideas around improved error handling. This is looking great though, thank you.

File: cmd/otel-allocator/server/server.go (hunk 5 above)
Comment (matej-g) [reply cmd/otel-allocator/server/server.go:95]: Sounds right to me, I initially wanted to keep behavior similar to what we have now, but returning last known good config is preferable to me as well.

**Comment by matej-g** [comment]
Thanks for the reviews @jaronoff97 @frzifus, this should be ready for another round 🙇

**Review by jaronoff97 — APPROVED** [review]
Looking great! I had one ask for another test for the new error behavior.

**Review by kristinapathak — APPROVED** [review]
looks great! 🥳

File: cmd/otel-allocator/target/discovery.go [hunk 7]
```diff
@@ -75,6 +79,21 @@ func (m *Discoverer) ApplyConfig(source allocatorWatcher.EventSource, cfg *confi
...
+	hash, err := hashstructure.Hash(m.jobToScrapeConfig, nil)
+	if err != nil {
+		return err
+	}
+	// If the hash has changed, updated stored hash and send the new config.
+	// Otherwise skip updating scrape configs.
+	if m.scrapeConfigsUpdater != nil && m.scrapeConfigsHash != hash {
+		err := m.scrapeConfigsUpdater.UpdateScrapeConfigResponse(m.jobToScrapeConfig)
+		if err != nil {
+			return err
```
[the remark this answers is not in the document]
Comment (matej-g) [reply cmd/otel-allocator/target/discovery.go:91]: That's a good idea, adding 👍

**Review by jaronoff97 — APPROVED** [review]
