### PR TITLE
Sort order of ports returned to fix flaky tests

### LINKED ISSUE #969: smoke-simplest e2e test fails intermittently
I have seen this on CI and can reproduce it on my laptop by running the test repeatedly.  The last time I did so it failed on the 11th iteration with the output below.  The key part is:  ".spec.ports.name: value mismatch, expected: jaeger-grpc != actual: otlp-grpc" as if it's confusing the jaeger-grpc and otlp-grpc ports.

```
=== RUN   kuttl/harness/smoke-simplest
=== PAUSE kuttl/harness/smoke-simplest
=== CONT  kuttl/harness/smoke-simplest
    logger.go:42: 10:29:06 | smoke-simplest | Creating namespace: kuttl-test-kind-kangaroo
    logger.go:42: 10:29:06 | smoke-simplest/0-install | starting test step 0-install
I0712 10:29:08.218699   29266 request.go:655] Throttling request took 1.045197889s, request: GET:https://192.168.64.2:8443/apis/discovery.k8s.io/v1beta1?timeout=32s
    logger.go:42: 10:29:08 | smoke-simplest/0-install | OpenTelemetryCollector:kuttl-test-kind-kangaroo/simplest created
    logger.go:42: 10:31:39 | smoke-simplest/0-install | test step failed 0-install
    case.go:361: failed in step 0-install
    case.go:363: --- Service:kuttl-test-kind-kangaroo/simplest-collector
        +++ Service:kuttl-test-kind-kangaroo/simplest-collector
        @@ -1,15 +1,85 @@
         apiVersion: v1
         kind: Service
         metadata:
        +  labels:
        +    app.kubernetes.io/component: opentelemetry-collector
        +    app.kubernetes.io/instance: kuttl-test-kind-kangaroo.simplest
        +    app.kubernetes.io/managed-by: opentelemetry-operator
        +    app.kubernetes.io/name: simplest-collector
        +    app.kubernetes.io/part-of: opentelemetry
        +    app.kubernetes.io/version: latest
        +  managedFields:
        +  - apiVersion: v1
        +    fieldsType: FieldsV1
        +    fieldsV1:
        +      f:metadata:
        +        f:labels:
        +          .: {}
        +          f:app.kubernetes.io/component: {}
        +          f:app.kubernetes.io/instance: {}
        +          f:app.kubernetes.io/managed-by: {}
        +          f:app.kubernetes.io/name: {}
        +          f:app.kubernetes.io/part-of: {}
        +          f:app.kubernetes.io/version: {}
        +        f:ownerReferences:
        +          .: {}
        +          k:{"uid":"dfc52c93-ed85-4cab-8953-0a02fe04c545"}: {}
        +      f:spec:
        +        f:internalTrafficPolicy: {}
        +        f:ports:
        +          .: {}
        +          k:{"port":4317,"protocol":"TCP"}:
        +            .: {}
        +            f:appProtocol: {}
        +            f:name: {}
        +            f:port: {}
        +            f:protocol: {}
        +            f:targetPort: {}
        +          k:{"port":4318,"protocol":"TCP"}:
        +            .: {}
        +            f:appProtocol: {}
        +            f:name: {}
        +            f:port: {}
        +            f:protocol: {}
        +            f:targetPort: {}
        +          k:{"port":14250,"protocol":"TCP"}:
        +            .: {}
        +            f:appProtocol: {}
        +            f:name: {}
        +            f:port: {}
        +            f:protocol: {}
        +            f:targetPort: {}
        +          k:{"port":55681,"protocol":"TCP"}:
        +            .: {}
        +            f:appProtocol: {}
        +            f:name: {}
        +            f:port: {}
        +            f:protocol: {}
        +            f:targetPort: {}
        +        f:selector: {}
        +        f:sessionAffinity: {}
        +        f:type: {}
        +    manager: manager
        +    operation: Update
        +    time: "2022-07-12T08:29:08Z"
           name: simplest-collector
           namespace: kuttl-test-kind-kangaroo
        +  ownerReferences:
        +  - apiVersion: opentelemetry.io/v1alpha1
        +    blockOwnerDeletion: true
        +    controller: true
        +    kind: OpenTelemetryCollector
        +    name: simplest
        +    uid: dfc52c93-ed85-4cab-8953-0a02fe04c545
         spec:
        +  clusterIP: 10.111.179.189
        +  clusterIPs:
        +  - 10.111.179.189
        +  internalTrafficPolicy: Cluster
        +  ipFamilies:
        +  - IPv4
        +  ipFamilyPolicy: SingleStack
           ports:
        -  - appProtocol: grpc
        -    name: jaeger-grpc
        -    port: 14250
        -    protocol: TCP
        -    targetPort: 14250
           - appProtocol: grpc
             name: otlp-grpc
             port: 4317
        @@ -25,4 +95,20 @@
             port: 55681
             protocol: TCP
             targetPort: 4318
        +  - appProtocol: grpc
        +    name: jaeger-grpc
        +    port: 14250
        +    protocol: TCP
        +    targetPort: 14250
        +  selector:
        +    app.kubernetes.io/component: opentelemetry-collector
        +    app.kubernetes.io/instance: kuttl-test-kind-kangaroo.simplest
        +    app.kubernetes.io/managed-by: opentelemetry-operator
        +    app.kubernetes.io/name: simplest-collector
        +    app.kubernetes.io/part-of: opentelemetry
        +    app.kubernetes.io/version: latest
        +  sessionAffinity: None
        +  type: ClusterIP
        +status:
        +  loadBalancer: {}


    case.go:363: resource Service:kuttl-test-kind-kangaroo/simplest-collector: .spec.ports.name: value mismatch, expected: jaeger-grpc != actual: otlp-grpc
Warning: events.k8s.io/v1beta1 Event is deprecated in v1.22+, unavailable in v1.25+
    logger.go:42: 10:31:39 | smoke-simplest | smoke-simplest events from ns kuttl-test-kind-kangaroo:
    logger.go:42: 10:31:39 | smoke-simplest | 2022-07-12 10:29:09 +0200 CEST	Normal	Pod simplest-collector-85b4bc9b74-g6b8f		Scheduled	Successfully assigned kuttl-test-kind-kangaroo/simplest-collector-85b4bc9b74-g6b8f to minikube
    logger.go:42: 10:31:39 | smoke-simplest | 2022-07-12 10:29:09 +0200 CEST	Normal	Pod simplest-collector-85b4bc9b74-g6b8f.spec.containers{otc-container}		Pulled	Container image "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.54.0" already present on machine
    logger.go:42: 10:31:39 | smoke-simplest | 2022-07-12 10:29:09 +0200 CEST	Normal	Pod simplest-collector-85b4bc9b74-g6b8f.spec.containers{otc-container}		Created	Created container otc-container
    logger.go:42: 10:31:39 | smoke-simplest | 2022-07-12 10:29:09 +0200 CEST	Normal	ReplicaSet.apps simplest-collector-85b4bc9b74		SuccessfulCreate	Created pod: simplest-collector-85b4bc9b74-g6b8f
    logger.go:42: 10:31:39 | smoke-simplest | 2022-07-12 10:29:09 +0200 CEST	Normal	Deployment.apps simplest-collector		ScalingReplicaSet	Scaled up replica set simplest-collector-85b4bc9b74 to 1
    logger.go:42: 10:31:39 | smoke-simplest | 2022-07-12 10:29:10 +0200 CEST	Normal	Pod simplest-collector-85b4bc9b74-g6b8f.spec.containers{otc-container}		Started	Started container otc-container
=== CONT  kuttl
    harness.go:402: run tests finished
    harness.go:511: cleaning up
    harness.go:568: removing temp folder: ""
--- FAIL: kuttl (165.93s)
    --- FAIL: kuttl/harness (0.00s)
        --- FAIL: kuttl/harness/smoke-simplest (152.86s)
FAIL
```

### PR DESCRIPTION
**Pull request by kevinearls**
Signed-off-by: Kevin Earls <kearls@redhat.com>

This should fix #969.  If there is more than one receiver defined, ports may be returned in a different order than that in which they were created.  Ideally they would always be in the same order as they are defined, but because Go does not guarantee order when iterating over keys from a map, we cannot guarantee this.

### CODE REVIEW

File: pkg/collector/adapters/config_to_ports.go [hunk 1]
```diff
@@ -60,28 +61,34 @@ func ConfigToReceiverPorts(logger logr.Logger, config map[interface{}]interface{
 		return nil, ErrReceiversNotAMap
 	}
 
+	sortedNames := make([]string, 0, len(receivers))
+	for name := range receivers {
+		sortedNames = append(sortedNames, name.(string))
```
Comment (frzifus) [inline pkg/collector/adapters/config_to_ports.go:66]: Would it make sense to check the type just for safety here?

```suggestion
		v, ok := name.(string)
		if !ok {
			logger.Warn("receiver does not match type, want: %s, got: %T", "string", name)
			continue
		}
		sortedNames = append(sortedNames, v)
```

File: pkg/collector/adapters/config_to_ports.go [hunk 2]
```diff
@@ -60,28 +61,34 @@ func ConfigToReceiverPorts(logger logr.Logger, config map[interface{}]interface{
 		return nil, ErrReceiversNotAMap
 	}
 
+	sortedNames := make([]string, 0, len(receivers))
```
Comment (pavolloffay) [inline pkg/collector/adapters/config_to_ports.go:64]: @kevinearls wouldn't it be cleaner to sort `ports` at the end of the function?

Comment (kevinearls) [reply pkg/collector/adapters/config_to_ports.go:64]: Maybe, but I'm not sure it necessary.  Originally when I saw this problem it occurred because we were getting receivers in the wrong order.  Sorting them alphabetically by name is fairly simple.

The ports, on the other hand, are in an array of corev1.ServicePort.  That does not implement methods needed to feed it to sort.Sort(), so sorting those would be non-trivial.

Comment (pavolloffay) [reply pkg/collector/adapters/config_to_ports.go:64]: What is the root cause of the problem? That the ports are not sorted or receivers? We should use the least error-prone approach:


Take a look at `sort.Slice`:

```
	sort.Slice(ports, func(i, j int) bool {
		return ports[i].Name > ports[j].Name
	})
```

Comment (kevinearls) [reply pkg/collector/adapters/config_to_ports.go:64]: The problem I had was caused by the receivers being in the wrong order, not the ports for a receiver.

**Review by frzifus — APPROVED** [review]
up to the others :)

**Comment by kevinearls** [comment]
@pavolloffay please review and merge if ok

File: pkg/collector/adapters/config_to_ports_test.go [hunk 3]
```diff
@@ -144,6 +144,39 @@ service:
 	}
 }
 
+func TestReceiverPortsSortedCorrectly(t *testing.T) {
```
Comment (pavolloffay) [inline pkg/collector/adapters/config_to_ports_test.go:147]: Thanks for the test! 

It would be better to change the `TestExtractPortsFromConfig` because it does the same thing - check what ports are returned and just change how the assert is written in that function (see my other comment).

File: pkg/collector/adapters/config_to_ports_test.go [hunk 4]
```diff
@@ -144,6 +144,39 @@ service:
...
+      receivers: [otlp, jaeger]
+      exporters: [logging]
+`
+	configuration, err := adapters.ConfigFromString(configurationString)
+	require.NoError(t, err)
+	require.NotEmpty(t, configuration)
+
+	ports, err := adapters.ConfigToReceiverPorts(logger, configuration)
+	assert.NoError(t, err)
+	assert.Len(t, ports, 4)
```
Comment (pavolloffay) [inline pkg/collector/adapters/config_to_ports_test.go:168]: This PR changes the semantics of `ConfigToReceiverPorts` - the expected result is strictly ordered, hence we can write a nice assert and compare slices directly:

```golang
assert.Equal(error, []v1.port{{Name: "foo", Port: 1778944}{...}}, got)
```

File: pkg/collector/adapters/config_to_ports.go [hunk 5]
```diff
@@ -60,32 +61,46 @@ func ConfigToReceiverPorts(logger logr.Logger, config map[interface{}]interface{
...
 			// should we break the process and return an error, or just ignore this faulty parser
 			// and let the other parsers add their ports to the service? right now, the best
 			// option seems to be to log the failures and move on, instead of failing them all
-			logger.Error(err, "parser for '%s' has returned an error: %w", rcvrName, err)
+			logger.Error(err, "parser for '%s' has returned an error: %w", name, err)
 			continue
 		}
 
 		if len(rcvrPorts) > 0 {
+			sort.Slice(ports, func(i, j int) bool {
```
Comment (pavolloffay) [inline pkg/collector/adapters/config_to_ports.go:101]: From all changes in this file only these 3 lines are needed 101-103 and move then right before the return.

File: pkg/collector/adapters/config_to_ports.go [hunk 6]
```diff
@@ -89,5 +90,12 @@ func ConfigToReceiverPorts(logger logr.Logger, config map[interface{}]interface{
 			ports = append(ports, rcvrPorts...)
 		}
 	}
+
+	if len(ports) > 0 {
```
Comment (pavolloffay) [inline pkg/collector/adapters/config_to_ports.go:94]: the check should not be needed

**Review by pavolloffay — APPROVED** [review]
