### PR TITLE
Fixed Labels with sha256 image ref

### LINKED ISSUE #1982: Image with digest causes labels validation error during reconcile (more than 63 characters)
Using an image including a `sha256` digest such as `otel/opentelemetry-collector-contrib@sha256:c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532`  or also `otel/opentelemetry-collector-contrib:0.81.0@sha256:c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532` generates an error when creating the k8s resources:
```
{
  "level": "error",
  "ts": "2023-08-03T16:43:59Z",
  "msg": "Reconciler error",
  "controller": "opentelemetrycollector",
  "controllerGroup": "opentelemetry.io",
  "controllerKind": "OpenTelemetryCollector",
  "OpenTelemetryCollector":
    { "name": "simplest", "namespace": "observability" },
  "namespace": "observability",
  "name": "simplest",
  "reconcileID": "518684fc-8052-4cd4-9c95-437fde1b07b6",
  "error": 'failed to reconcile the expected configmaps: failed to create: ConfigMap "simplest-collector" is invalid: metadata.labels: Invalid value: "c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532": must be no more than 63 characters',
  "stacktrace":
    "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226",
}

```

Looking at the stacktrace this is likely caused by the common labels set on all resources not accounting for the 63 char limit on the version: 
https://github.com/open-telemetry/opentelemetry-operator/blob/440f7a733ae09d8683b4d1af423231e52308ac19/internal/manifests/collector/labels.go#L50-L55

Here is a full example for reproduction:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: otel/opentelemetry-collector-contrib:0.81.0@sha256:c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```

### PR DESCRIPTION
**Pull request by yuriolisa**
**Description:** <Describe what has changed.>

Fixed the labeling process which was broken at the moment to capture the current image tag when the users set the sha256 reference.

**Link to tracking Issue:** <Issue number if applicable>
resolves #1982 

**Testing:** <Describe what testing was performed and which tests were added.>
Created a test using an image being declared with a sha256 and checked if there was a label with only the version number. 

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by swiatekm-sumo — APPROVED** [review]

File: internal/manifests/collector/labels_test.go [hunk 1]
```diff
@@ -49,7 +49,26 @@ func TestLabelsCommonSet(t *testing.T) {
...
 }
+func TestLabelsSha256Set(t *testing.T) {
+	// prepare
+	otelcol := v1alpha1.OpenTelemetryCollector{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      collectorName,
+			Namespace: collectorNamespace,
+		},
+		Spec: v1alpha1.OpenTelemetryCollectorSpec{
+			Image: "ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.81.0@sha256:c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532",
```
Comment (pavolloffay) [inline internal/manifests/collector/labels_test.go:60]: Could you please add a test case for `otel/opentelemetry-collector-contrib@sha256:c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532` - it was reported in the issue this PR resolves

**Review by tcoville-coveo — APPROVED** [review]
Thanks for addressing this issue ! :)

**Review by pavolloffay — APPROVED** [review]
