### PR TITLE
Set env vars correctly in workflow steps

### LINKED ISSUE #150: Build args not being used correctly in the container images
The change in the way the containers are built caused the build-args to not work anymore, affecting 0.17.0:

```
{"level":"info","ts":1608198341.9267085,"msg":"Starting the OpenTelemetry Operator","opentelemetry-operator":"${VERSION}","opentelemetry-collector":"${OTELCOL_VERSION}","build-date":"${VERSION_DATE}","go-version":"go1.13.15","go-arch":"amd64","go-os":"linux"}
...
{"level":"error","ts":1608198360.427475,"logger":"upgrade","msg":"failed to parse version for OpenTelemetry Collector instance","name":"simplest","namespace":"opentelemetry-operator-system","version":"${OTELCOL_VERSION}","error":"Invalid Semantic Version","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/open-telemetry/opentelemetry-operator/pkg/collector/upgrade.ManagedInstance\n\t/workspace/pkg/collector/upgrade/upgrade.go:89\ngithub.com/open-telemetry/opentelemetry-operator/pkg/collector/upgrade.ManagedInstances\n\t/workspace/pkg/collector/upgrade/upgrade.go:47\nmain.main.func2\n\t/workspace/main.go:141\nsigs.k8s.io/controller-runtime/pkg/manager.RunnableFunc.Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/manager.go:294\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:691"}
```

### PR DESCRIPTION
**Pull request by jpkrohling**
Fixes #150
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This should now work: 
image

File: main.go [hunk 1]
```diff
@@ -70,6 +70,18 @@ func main() {
 
 	// Add flags related to this operator
 	v := version.Get()
+	logger := zap.New(zap.UseFlagOptions(&opts))
```
Comment (jpkrohling) [inline main.go:73]: This has been moved here so that it logs the versions even when a Kubernetes isn't available.
